### ISSUE TITLE
查找不到回复

### ISSUE THREAD

**Issue by mr-cn** [sciooga/v2ex-plus#103]
![image](https://user-images.githubusercontent.com/19818121/59814953-9bf60c80-9349-11e9-910a-7b2fe86d2415.png)

原帖地址：https://www.v2ex.com/t/575287?p=1

**Comment by sciooga** [comment]
你好，该问题很可能和你屏蔽用户，或 V2EX 的评论列表缓存有关系

发自我的 iPhone

**Comment by mr-cn** [comment]
在他的上面的上面便是那个人的回复……

已确认没有Block（不然也不会看得见他的回复）

**Comment by sciooga** [comment]
![image](https://user-images.githubusercontent.com/9958281/59823936-51cd5500-9362-11e9-83cf-fb6969249d14.png)

**Comment by mr-cn** [comment]
Chromium(Windows) 版本 77.0.3831.0
怎么 Debug？我这一直显示没这个回复，但是事实上回复就在他隔壁……

**Comment by mr-cn** [comment]
点击会话详情显示
![image](https://user-images.githubusercontent.com/19818121/59824129-d1f3ba80-9362-11e9-9dcc-23494be5ed1c.png)
点进去是
![image](https://user-images.githubusercontent.com/19818121/59824148-dd46e600-9362-11e9-993a-7b184ccf1096.png)
```
//如果被@用户只有一条回复但回复是@其他不相干用户则显示这条回复
                if ( _no-1 == r_i && !have_main_reply && /(\S+?) 回复于\d+层/.exec(_replyDetail.children(".leftBubble").last().find(".bubbleName").text())[1] == at_name ){
                    _replyDetail.children(".leftBubble").last().removeClass("unrelated");
                }
```
这一部分

**Comment by sciooga** [comment]
你的扩展版本号是？

**Comment by mr-cn** [comment]
1.3.9

**Comment by sciooga** [comment]
我们小组都无法复现...
你快速预览其他也是这样吗

**Comment by mr-cn** [comment]
不是 就这一个

**Comment by mr-cn** [comment]
其实我也无所谓，偶尔遇到了，想着报告一下😂

很麻烦就算了，你当作没看见吧- -

**Comment by sciooga** [comment]
主要是我们这边无法复现，如果你方便的话，可以尝试帮我们定位一下问题？

**Comment by mr-cn** [comment]
没有问题。。但是我没怎么接触过前端，你可能得指导一下。。。

**Comment by sciooga** [comment]
麻烦邮件联系一下

**Comment by mr-cn** [comment]
sorry啊，chromium用不惯，已经换成firefox了，在firefox上没有复现问题
 
------------------ Original ------------------
