### ISSUE TITLE
部分CDN 节点报错

### ISSUE THREAD

**Issue by ldong** [sciooga/v2ex-plus#104]
目前 sjc.v2ex.com 这个节点已经不能用了, 我测试了下 lax.v2ex.com 也是失效的. 

![image](https://user-images.githubusercontent.com/5491695/59972399-2b1a4480-9543-11e9-8d3b-760c781c4c34.png)

直接关掉自定义节点, 或者目前可以参考这个帖子: https://www.v2ex.com/t/559587 
用这个 `https://global.v2ex.com` 节点可以访问成功. 不清楚有没有一种方法能够支持动态更新节点. 

https://github.com/sciooga/v2ex-plus/blob/7e4497bc4c32f69ba4442c7c3f4c4a8490bd20fa/page/options.html#L241

:smile:

**Comment by sciooga** [comment]
自定义节点可以考虑

**Comment by sciooga** [comment]
已经更新
