### ISSUE TITLE
Ctrl + Tab 无法跳转到下一个标签页

### ISSUE THREAD

**Issue by liyuhang1997** [sciooga/v2ex-plus#106]
期望：Ctrl + Tab 跳转到下一个打开的标签页 / Ctrl + Shift + Tab 跳转到上一个打开的标签页。

实际：Ctrl + Tab / Ctrl + Shift + Tab跳转到 V2EX 页面的输入区域。

注：按 Tab 同样是跳转到 V2EX 页面的输入区域，不知道为什么 Ctrl + Tab 也给跳转了。改用另外一组快捷键 Ctrl + PgDn / Ctrl + PgUp 是没有问题的。

**Comment by sciooga** [comment]
扩展监听了 Tab 按键的事件，可能引起了冲突

**Comment by Higurashi-kagome** [comment]
我使用插件时并没有遇到这个问题，也就是 Ctrl + Tab 和 Ctrl + Shift + Tab 快捷键能够正常切换标签页，只有在单独按 Tab 键时才会在顶部与输入框之间跳转。 @liyuhang1997

**Comment by snowman** [comment]
same here, please `jump to reply` only when none of `Ctrl`, `Shift`, `Alt` is pressed
