### ISSUE TITLE
小部分情况下，仍然无法对 @somone 作出正常的反映

### ISSUE THREAD

**Issue by Zhang-Siyang** [sciooga/v2ex-plus#108]
这个标题我是真的不知道该怎么起了

症状请看截图：
![image](https://user-images.githubusercontent.com/22904269/61169287-0f2c2080-a58e-11e9-8812-4a66a6272dcc.png)

很显然，应该显示的回复就在咫尺之隔，但是没有显示。

帖子是 https://www.v2ex.com/t/580847

**Comment by Zhang-Siyang** [comment]
忘了说，我是之前就在工单系统提过工单的@CEBBCAT，不知道是不是整体编程思路有问题呢？没读过您的源码不好多加揣测，哈哈

谢谢您长久以来的付出，BUG不着急修哈

**Comment by p0we7** [comment]
你所述问题无法复现 ，请问你扩展版本是什么？

**Comment by Zhang-Siyang** [comment]
版本是 1.4.0

是我屏蔽用户太多了？好像也才几十个（不多吧？哈哈）

**Comment by sciooga** [comment]
昨晚发布了一个新版，麻烦再试试？

发自我的 iPhone

**Comment by Zhang-Siyang** [comment]
嗯，后台看了看，确实到了1.4.1了。

不过还是不可以，和上面截图行为一致，console也没有报错。

我把其他拓展都关了，重启了Chrome，然后开console，刷新网页，点击显示对话详情，这时出现一个错误，我截图了，希望对你有帮助：

![image](https://user-images.githubusercontent.com/22904269/61183784-0d3e8c00-a678-11e9-9aea-1b46a3bd83a4.png)

**Comment by Zhang-Siyang** [comment]
今天试了时，我这边还不可以，打开F12刷新网页，console非常干净，移动鼠标到 @someone ， console跳出：

> The resource https://pagead2.googlesyndication.com/pagead/js/r20190715/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

不知道有没有关系

**Comment by sciooga** [comment]
这个问题找到原因了，确实和屏蔽用户有关系，等待修复（还稍微有点麻烦）

**Comment by Zhang-Siyang** [comment]
作者大大，这个问题好像还时有出现，我不是很了解开源项目的运作模式，还是应该保持这个issue的开启吗？

**Comment by p0we7** [comment]
@Zhang-Siyang 留着不用关， 现在还没有人有空修 bug 。

**Comment by p0we7** [comment]
这个问题貌似已经修复了？

**Comment by Zhang-Siyang** [comment]
> 这个问题貌似已经修复了？

![image](https://user-images.githubusercontent.com/22904269/75049099-90746a00-5504-11ea-930b-d41ab730047c.png)
![image](https://user-images.githubusercontent.com/22904269/75049115-99653b80-5504-11ea-9854-c6181f6c15cb.png)
看起来并没有

**Comment by p0we7** [comment]
> > 这个问题貌似已经修复了？
> 
> ![image](https://user-images.githubusercontent.com/22904269/75049099-90746a00-5504-11ea-930b-d41ab730047c.png)
> ![image](https://user-images.githubusercontent.com/22904269/75049115-99653b80-5504-11ea-9854-c6181f6c15cb.png)
> 看起来并没有

![image](https://user-images.githubusercontent.com/8407573/75238345-d0389b80-57fb-11ea-8565-279b9bd8022e.png)

**Comment by Zhang-Siyang** [comment]
我这里仍然提示未发现回复，我怀疑可能是我屏蔽列表的原因，关闭了吧

浏览器是 Chrome 80.0.3987.122 (Official Build) (64-bit)
这条回复由Windows 10 专业版发出，之前有时候是拿 Manjaro 测试的。
刚才测试时插件版本是 1.4.4
