### ISSUE TITLE
插件的表情全部失效

### ISSUE THREAD

**Issue by curx95** [sciooga/v2ex-plus#109]
由于新浪现在不允许外链，而插件的表情都是新浪外链的，故全部失效。希望可以更换表情的链接

**Comment by sciooga** [comment]
尝试过想换到 V 站自己的图床，但是个人账号的图片数量有限制，你这边能上传到 V 站图床吗

**Comment by curx95** [comment]
> 尝试过想换到 V 站自己的图床，但是个人账号的图片数量有限制，你这边能上传到 V 站图床吗

我也没有权限，V站自有图床需要充值才会开放。考虑联系下站长，获取一些支持？

**Comment by sciooga** [comment]
那就有些困难了，这部分我想想办法

**Comment by wsgzao** [comment]
作者是否考虑使用GitHub作为表情图床呢

**Comment by gexiao** [comment]
表情失效的问题太严重，我来把已有的表情都传到 V2EX 自己的图床上好了，等会儿把链接贴过来。
但是这样的话后续插件里想增加新的表情会比较麻烦，得手动处理。

**Comment by gexiao** [comment]
1.jpg https://i.v2ex.co/8oRV15Jy.png
2.jpg https://i.v2ex.co/9n9Ya75P.png
3.jpg https://i.v2ex.co/j4r79fiI.png
4.jpg https://i.v2ex.co/x867Mwqp.png
5.jpg https://i.v2ex.co/wITAgO6V.png
6.jpg https://i.v2ex.co/0BiZ83YV.png
7.jpg https://i.v2ex.co/946oH9ug.png
8.jpg https://i.v2ex.co/J7slPvg5.png
9.jpg https://i.v2ex.co/HQitjRsV.png
10.jpg https://i.v2ex.co/6qkEmGZF.png
11.jpg https://i.v2ex.co/VZ7jf9my.png
12.jpg https://i.v2ex.co/LEIWqZdu.png
13.jpg https://i.v2ex.co/yz4KxCP6.png
14.jpg https://i.v2ex.co/37nCwTP4.png
15.jpg https://i.v2ex.co/sqToHiDZ.png
16.jpg https://i.v2ex.co/9Ndn75sI.png
17.jpg https://i.v2ex.co/ob562zBU.png
18.jpg https://i.v2ex.co/FJ3A9q18.png
19.jpg https://i.v2ex.co/Thy5Oqk6.png
20.jpg https://i.v2ex.co/uN704852.png
21.jpg https://i.v2ex.co/o2nq1EN2.png
22.jpg https://i.v2ex.co/5Aap1iN6.png
23.jpg https://i.v2ex.co/88Qu418X.png
24.jpg https://i.v2ex.co/cX2ligJM.png
25.jpg https://i.v2ex.co/0shfB89W.png
26.jpg https://i.v2ex.co/6IBSQ8xv.png
27.jpg https://i.v2ex.co/9j4yR89H.png
28.jpg https://i.v2ex.co/u7E0N0mV.png
29.jpg https://i.v2ex.co/2rPV8B6J.png
30.jpg https://i.v2ex.co/9kZ3y873.png
31.jpg https://i.v2ex.co/ROBUTUW7.png
32.jpg https://i.v2ex.co/MsV5eSJ5.png
33.jpg https://i.v2ex.co/W979C9Ry.png
34.jpg https://i.v2ex.co/PeEcsF6x.png
35.jpg https://i.v2ex.co/qjH0raTX.png
36.jpg https://i.v2ex.co/7QYI6CMn.png
37.jpg https://i.v2ex.co/BlBl22Ow.png
38.jpg https://i.v2ex.co/OJTA1nf8.png
39.jpg https://i.v2ex.co/ni1vw0o2.png
40.jpg https://i.v2ex.co/504J5BO2.png
41.jpg https://i.v2ex.co/92IL9xOI.jpeg
42.jpg https://i.v2ex.co/oJ951Htz.jpeg

FYI @sciooga

**Comment by p0we7** [comment]
如果有空的话你可以提供一个 PR 帮忙处理一下，之前几个代码贡献者更新时间不多偶尔才上来一次。
@bynil
