### ISSUE TITLE
启用扩展后无法登录登出

### ISSUE THREAD

**Issue by liyuhang1997** [sciooga/v2ex-plus#110]
输入用户名和密码点击登陆后依然是未登录状态，没有提示。停用 v2ex plus 扩展后正常。

另外也无法登出，V2EX 提示："登出过程中遇到一些问题，请点击下面的按钮重试"。停用 v2ex plus 扩展后正常。

**Comment by p0we7** [comment]
暂无法复现你的问题。
现在最新版本为 1.4.1

**Comment by sciooga** [comment]
已经解决，与自定义节点功能相冲突（所以没启用自定义节点的同学是不会遇到这个问题无法复现的），这两天更新
