### ISSUE TITLE
期望一个新feature：查看有谁@了该用户

### ISSUE THREAD

**Issue by Zhang-Siyang** [sciooga/v2ex-plus#111]
想到这个是因为[有的朋友的言论](https://www.v2ex.com/t/594210#r_7797754)违反至少我的常识，我想发言和他讨论，但又怕已经有人反对过他造成不必要的回帖

我想这个功能可以做到：点击该回复的一个按钮，可以出现类似会话详情的功能，也即列出回复该回复的回复

不知道这么说你能不能听懂，哈哈

祝好

**Comment by p0we7** [comment]
有能力的话建议直接 PR 代码。
本项目开发者都是业余贡献代码，最近他们都比较忙。

**Comment by Zhang-Siyang** [comment]
@p0we7  我努力
