### ISSUE TITLE
[讨论] 没有网络的情况下不打卡

### ISSUE THREAD

**Issue by tjx666** [sciooga/v2ex-plus#115]
每天打开电脑就是网络错误，1 小时后重新打卡，很烦。如果大家也这样觉得，我愿意改下代码提个 PR.

**Comment by sciooga** [comment]
你好，确实存在你所说的情况，你看看是否能修复？

发自我的iPhone

**Comment by tjx666** [comment]
这两天我抽空处理下

**Comment by tjx666** [comment]
@sciooga 这两天我抽空处理下

**Comment by tjx666** [comment]
已提交 [pr#116](https://github.com/sciooga/v2ex-plus/pull/116) @sciooga

**Comment by ilaipi** [comment]
最近也是为这个弹窗烦恼，感谢处理~ @tjx666

**Comment by tjx666** [comment]
https://github.com/sciooga/v2ex-plus/pull/116
