### ISSUE TITLE
一键签到导致个性化CSS无法显示签到

### ISSUE THREAD

**Issue by zwpaper** [sciooga/v2ex-plus#12]
我使用了

```
@import url("//dn-startplay.qbox.me/v2ex-material-theme2/v2ex.min.css");
```

作为个性化CSS，但是由于一键签到会个性签到部分，导致无法正常显示签到的按钮。

OS X 10.11
Chome 49

**Comment by sciooga** [comment]
我有两个建议，一个是你启用扩展的自动签到功能，另一个是保存手动签到的页面至书签栏。

扩展兼容这个样式是有些麻烦的...

**Comment by zwpaper** [comment]
我开自动签到了，但是没有效果...重新关了再开也试过了
有什么办法能知道自动签到是否生效吗？

**Comment by sciooga** [comment]
自动签到是每隔一小时尝试一次，在未签到成功前每次尝试无论成功与否都会有提示，并不是你打开自动签到就立即会尝试签到的。

**Comment by zwpaper** [comment]
那问题就变成为什么不自动签到了。。。我Chrome一直开着，v2ex的页面有时也会开着，但是一直都没有签到，是需要什么触发条件吗？或者我可以从哪里找到相关信息？
问题多了点，抱歉。

**Comment by sciooga** [comment]
你可以尝试查看下扩展的 console 是否有出错提示：打开扩展管理页面（chrome://extensions/），勾选最右上方的开发者模式，找到并打开 v2ex plus 的背景页查看控制台信息。
![image](https://cloud.githubusercontent.com/assets/9958281/14021547/e2c8a7d0-f216-11e5-914b-bb41c7369aa7.png)
这是签到成功后再次尝试的日志。

不客气的。

**Comment by zwpaper** [comment]
突然又可以自动签到了，但是没有看到你说的日志。先关闭了吧，谢谢了！
