### ISSUE TITLE
请问是否考虑支持 Firefox ESR 版本？

### ISSUE THREAD

**Issue by MoienBowen** [sciooga/v2ex-plus#122]
目前 v2ex-plus Firefox Extension 最低支持 69.0 版本。

最新的 Firefox ESR 版本为 68.5.0 [Release Notes](https://www.mozilla.org/en-US/firefox/68.5.0/releasenotes/)

由于企业安全策略等限制，无法自行升级或更改版本。

在不考虑更换浏览器或安装绿色版本的前提下，请问作者是否会考虑向下兼容呢？

谢谢。

**Comment by p0we7** [comment]
下次更新看看

**Comment by p0we7** [comment]
我看了下现在的的[代码](https://github.com/sciooga/v2ex-plus/blob/001830752f92f117b0d3e2edcb7b3725687095b1/manifest.json#L64-L67) ， 现在最低是支持 68 版本的， 也不能用吗？

**Comment by MoienBowen** [comment]
> 
> 
> 我看了下现在的的[代码](https://github.com/sciooga/v2ex-plus/blob/001830752f92f117b0d3e2edcb7b3725687095b1/manifest.json#L64-L67) ， 现在最低是支持 68 版本的， 也不能用吗？

目前已经可以使用，感谢！
拓展非常实用，加油！~ :)
