### ISSUE TITLE
QQ浏览器装了这个插件后，选择地址栏内容，按Ctrl+C，失效，无法复制

### ISSUE THREAD

**Issue by scoful** [sciooga/v2ex-plus#124]
RT，麻烦看看，排查了好久才发现是这个插件导致的，hhh

**Comment by scoful** [comment]
大概翻完了这个插件的代码，没看到有啥会影响的呀，但是开着插件就是不能Ctrl+C地址栏的内容，关了就可以，为啥啊，黑人问号脸

**Comment by p0we7** [comment]
@scoful 确定不是 qq浏览器的问题？

**Comment by scoful** [comment]
@p0we7 方便测试一下么？你那边试试?

**Comment by p0we7** [comment]
> @p0we7 方便测试一下么？你那边试试?

我这现在没有QQ浏览器有空再试试

**Comment by scoful** [comment]
@p0we7 找到原因了，manifest.json配置的默认的快捷键Ctrl+B，跟浏览器本身的快捷键冲突了，然后就莫名其妙出了这个bug，QQ浏览器啊。
