### ISSUE TITLE
每次打开chrome就弹出：罕见错误，请联系开发者。

### ISSUE THREAD

**Issue by livc** [sciooga/v2ex-plus#13]
怎么破

**Comment by sciooga** [comment]
关闭自动签到就不会有这个提示

**Comment by livc** [comment]
我知道，但是有其他解决方法吗

**Comment by sciooga** [comment]
产生这个问题的原因是签到时会发起一个请求获取一个 token 然后用这个 token 再发起一次请求进行签到，当第二次请求返回的不是签到成功时便会产生这个提示，具体原因不明，或许更网络变更有关系？我会尝试解决这个问题，但是调试起来很困难。

你有什么建议吗？
