### ISSUE TITLE
v2ex无法连接或者连接困难时（日常抽风），FireFox会陷入一段时间的高CPU、高内存占用、且无响应或近乎假死的状态

### ISSUE THREAD

**Issue by mo-han** [sciooga/v2ex-plus#131]
禁用此模块则不会出现此现象，接入对v2ex相对友好的运营商线路时也不会出现此现象

是否是因为采用了激进的超时重试机制，导致短时间内浏览器发起巨大数量的连接

**Comment by sciooga** [comment]
暂时定位不到问题

**Comment by mo-han** [comment]
> 
> 
> 暂时定位不到问题

我很久前就把通知、签到之类需要定时连接的功能都关闭了，凑合用着

**Comment by sciooga** [comment]
我似乎理解你的意思了，是断网很长一段时间后，打开浏览器才能复现是吗？这个是已知 bug
