### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by realpg** [sciooga/v2ex-plus#133]
新浪图床开启防盗链了，但是V2仍然有大量旧帖子采用新浪图床

是否考虑集成一个modheader的小功能

匹配这个功能：

![image](https://user-images.githubusercontent.com/12572518/89116370-058d9780-d4c6-11ea-88df-dd2b9dab9864.png)

大概所需权限是sinaimg.cn域名访问权

然后匹配这个域名，把header里面的referer去掉即可

**Comment by p0we7** [comment]
建议直接提交 PR ，现在提 issue 没有人有空搞。

**Comment by sciooga** [comment]
已经有 pr 实现，等待发版
