### ISSUE TITLE
2020921-编辑栏上方的表情与sov2ex无法使用了

### ISSUE THREAD

**Issue by CallMeReznov** [sciooga/v2ex-plus#138]
2020921-编辑栏上方的表情与sov2ex无法使用了，请问作者这是什么情况？

**Comment by blueandhack** [comment]
我的感觉可能和这个站长更新有关

[新的顶部搜索框](https://v2ex.com/t/706599#reply0)

**Comment by p0we7** [comment]
#137 fix
