### ISSUE TITLE
鉴于图床很多效果不是太好，可否支持V2本身的收费图床呢？

### ISSUE THREAD

**Issue by CallMeReznov** [sciooga/v2ex-plus#141]
图床失效的失效，需要翻墙的翻墙。 
所以特意购买了V2的VIP可以使用V2的图床。

可否添加支持V2的收费图床呢？

**Comment by p0we7** [comment]
暂时没有开发者有空，有能力建议直接提交 PR

**Comment by sciooga** [comment]
V 站目前处于被墙状态，2.0 版本只支持 imgur 免费图床
