### ISSUE TITLE
[bug report]开启“使用sov2ex搜索”时，搜索会打开两个窗口，一个是V站调的Google搜索，一个是sovex

### ISSUE THREAD

**Issue by hsingll** [sciooga/v2ex-plus#146]
如题

**Comment by p0we7** [comment]
没遇到过这个问题，你是什么Windows、chrome、v2ex plus 版本?

**Comment by hsingll** [comment]
> 没遇到过这个问题，你是什么Windows、chrome、v2ex plus 版本?

macOS 14.6
Chrome 86.0.4240.111
v2ex plus 1.4.8

**Comment by p0we7** [comment]
@satorioh V2 现在增加一个图片红框的下拉菜单导致的按下回车之后会同时打开 Google 和 sov2ex 两个页面，有时间优化一下吗？
![image](https://user-images.githubusercontent.com/8407573/97521890-72d39a80-19d9-11eb-8d62-a7175a019e2f.png)

**Comment by p0we7** [comment]
@hsingll 有可能 v2 更新来回车的逻辑了， 上两个星期还是正常的。

**Comment by sciooga** [comment]
已经解决，等待更新推送
