### ISSUE TITLE
列表预览按钮无效

### ISSUE THREAD

**Issue by quericy** [sciooga/v2ex-plus#15]
错误提示:Uncaught ReferenceError: hljs is not defined

![http://i.imgur.com/gNGIMj2g.png](http://i.imgur.com/gNGIMj2g.png)

**Comment by sciooga** [comment]
早几天的 commit 已经解决，这两天会发布1.0版本。

问题是由于 V 站新加入了主题代码高亮的功能，现在已经做好兼容（预览只能去除代码高亮）。
