### ISSUE TITLE
提升按钮与链接的可访问性（Accessibility）

### ISSUE THREAD

**Issue by EnixCoda** [sciooga/v2ex-plus#150]
感谢开发这个插件！在使用过程中发现一个或许可以提升用户体验的点——

对于“展开主题”、“楼层直链”等按钮与链接，是否可以考虑把它们的 HTML 元素分别替换为 `button` 与 `a` 等符合语义的元素以提升可访问性？

如果作者近期繁忙，我有一定的浏览器插件开发经验，可以帮忙进行初步的修改并提交 PR : )

**Comment by p0we7** [comment]
嗯 直接提交就好
