### ISSUE TITLE
近期频繁失效, 卸载重装能正常使用，重启chrome后马上失效，报错找不到 jQuery 符号 $

### ISSUE THREAD

**Issue by linyongfu2013** [sciooga/v2ex-plus#152]
chrome :  89.0.4389.90
插件版本：应用市场最新版本

**Comment by yongxin1024** [comment]
+1
报错信息：
v2ex_reply.js:62 Uncaught ReferenceError: $ is not defined

**Comment by p0we7** [comment]
提供的信息太小，无法判断问题。

**Comment by linyongfu2013** [comment]
> 提供的信息太小，无法判断问题。

卸载后重装能用，重启 chrome 后马上失效，控制台日志就是二楼所说，找不到 jQuery 那个符号

**Comment by sciooga** [comment]
@xiaoxinshiwo 我们无法复现，可能需要你帮忙定位下问题

**Comment by yongxin1024** [comment]
![image](https://user-images.githubusercontent.com/24218496/113818536-79491800-97aa-11eb-8b93-be3151d9a030.png)

**Comment by yongxin1024** [comment]
> @xiaoxinshiwo 我们无法复现，可能需要你帮忙定位下问题

怎么帮助呢？

**Comment by CloudnuY** [comment]
> @xiaoxinshiwo 我们无法复现，可能需要你帮忙定位下问题

同样问题，Chrome商店最新版本插件，Edge最新正式版，经过如下测试：

* 禁用所有插件，保留v2ex-plus，刷新页面，问题依旧
* 禁用所有插件，禁用v2ex-plus，刷新页面，启用v2ex-plus，问题依旧
* 保持所有插件，在浏览器扩展设置里面允许v2ex-plus在InPrivate窗口使用，刷新页面，问题解决
* 接上条测试，关闭浏览器，重新打开浏览器，问题复现
* 接上条测试，在浏览器扩展设置里面禁止v2ex-plus在InPrivate窗口使用，刷新页面，问题解决

**Comment by p0we7** [comment]
@CloudnuY 扩展版本号是多少？

**Comment by linyongfu2013** [comment]
版本：1.4.7，就是应用商店里最新那个

**Comment by CloudnuY** [comment]
> @CloudnuY 扩展版本号是多少？

扩展版本 1.6.0
Edge  89.0.774.68

**Comment by p0we7** [comment]
建议录个视频复现一下问题，我们没法复现。

**Comment by linyongfu2013** [comment]
我这里好像莫名其妙突然好了。。:doge

**Comment by lanjuzi** [comment]
> > @xiaoxinshiwo 我们无法复现，可能需要你帮忙定位下问题
> 
> 同样问题，Chrome商店最新版本插件，Edge最新正式版，经过如下测试：
> 
> * 禁用所有插件，保留v2ex-plus，刷新页面，问题依旧
> * 禁用所有插件，禁用v2ex-plus，刷新页面，启用v2ex-plus，问题依旧
> * 保持所有插件，在浏览器扩展设置里面允许v2ex-plus在InPrivate窗口使用，刷新页面，问题解决
> * 接上条测试，关闭浏览器，重新打开浏览器，问题复现
> * 接上条测试，在浏览器扩展设置里面禁止v2ex-plus在InPrivate窗口使用，刷新页面，问题解决

同样的问题，所有测试步骤全部一致
每次开启或者关闭InPrivate下的权限后问题解决，重启浏览器后复现

扩展版本 1.6.0
Chrome版本 90.0.4430.72（正式版本） (x86_64)

**Comment by BadApple9** [comment]
+1

扩展版本：1.6.0
Chrome 版本：89.0.4389.128（正式版本） (x86_64)

**Comment by lanjuzi** [comment]
本地扩展安装正常，应用市场安装的版本会出现问题

**Comment by p0we7** [comment]
> 本地扩展安装正常，应用市场安装的版本会出现问题

测试过无论是否登陆 v2 账号，均无法复现报错找不到 jQuery 符号的错误。

macOS 通过 Cmd + Q 退出 Chrome 再打开，扩展依然正常。



> 建议录个视频复现一下问题，我们没法复现。

**Comment by linyongfu2013** [comment]
我这边突然正常能使用了，先关闭该 issue了，其他人还有问题再另外开一个吧。

**Comment by wysnxzm** [comment]
问题存在
开启隐私模式访问后正常

**Comment by yejinmo** [comment]
问题依旧存在

扩展版本：1.6.0
Chrome 版本：92.0.4515.131（正式版本） （64 位）

**Comment by p0we7** [comment]
复现不到，提供详细复现流程。---- On 星期五, 23 七月 2021 17:00:07 +0800  ***@***.******@***.***> wrote ----  
问题存在

**Comment by KKFantasy** [comment]
同样的问题，切换隐私模式下访问选项后恢复，再重启chrome又会失效。

**Comment by zhangnew** [comment]
1.6.6 版本 问题依然存在，Chrome 102，允许在无痕模式下使用可以恢复
