### ISSUE TITLE
插件经常失效chrome下

### ISSUE THREAD

**Issue by mainjzb** [sciooga/v2ex-plus#153]
![image](https://user-images.githubusercontent.com/12838339/119917819-d9359100-bf99-11eb-9e8c-b258035e6fb0.png)
之前一直在用edge，没啥问题。自从换回了chrome （版本90-91都这样），就一直都会出现插件失灵的效果，点了收集错误之后的内容是上面的图。一般都是重新安装一次插件，能用个5个小时的，然后又失效了。我主要用插件来看楼层回复。同一机子下edge倒是没啥问题。
电脑系统win10：20H2（19042.985）
当前chrome版本： 91.0.4472.77
电脑无杀毒软件，切换过网络。系统也更新过。

**Comment by omitor** [comment]
确实，在chrome91版本报错，在edge正常使用。

**Comment by p0we7** [comment]
用了 chrome 4、5天没发现问题（只装了本插件，只用来访问 v2）。

**Comment by aa65535** [comment]
```
17:39:21.254 emoticon.js:50 Uncaught ReferenceError: $ is not defined
    at emoticon.js:50
17:39:21.256 v2ex_reply.js:62 Uncaught ReferenceError: $ is not defined
    at v2ex_reply.js:62
17:39:21.256 user_info.js:29 Uncaught ReferenceError: $ is not defined
    at user_info.js:29
17:39:21.256 v2ex_date.js:2 Uncaught ReferenceError: $ is not defined
    at v2ex_date.js:2
```

的确有问题，新安装的可以用，重启一下浏览器就报错。

**Comment by aa65535** [comment]
换回 `1.6.0` 就正常了。

**Comment by Jed-Z** [comment]
同样出现了这个问题，Windows和macOS上的Chrome都一样，Chrome版本93.0.4577.82

**Comment by sciooga** [comment]
需要再给一些时间进行测试，目前一直不能复现，有可能是插件自带的 jQuery 版本有些不兼容

**Comment by mainjzb** [comment]
![QQ截图20211013174516](https://user-images.githubusercontent.com/12838339/137109459-cf963061-848c-4da0-a57b-4129a6ff842d.png)

**Comment by jhxxs** [comment]
edge上也有这个问题，刚装上的时候正常，用几天后会突然失效，也是控制台报`$ is not defined`错误
![image](https://user-images.githubusercontent.com/7448223/143797440-9ea5db70-cb46-483b-ad4f-27820906f4df.png)

**Comment by zhangnew** [comment]
1.6.6 版本 问题依然存在，Chrome 102，允许在无痕模式下使用可以恢复
