### ISSUE TITLE
请发布最新的Firefox版本

### ISSUE THREAD

**Issue by libook** [sciooga/v2ex-plus#155]
Firefox上还是1.4，很久没发布新版了，请更新一下吧~

**Comment by sciooga** [comment]
你好，firefox 已经可以安装 chrome 版本，所以停止了单独的版本更新

发自我的iPhone

**Comment by libook** [comment]
我是希望能更新到Firefox的add-ons平台上，因为涉及到多设备同步，所以最好不需要手动一个一个地安装。

**Comment by libook** [comment]
@sciooga 
https://addons.mozilla.org/zh-CN/firefox/addon/v2ex-plus9/
就是这个，目前版本是1.4.6，希望能发布最新的1.6版本。

**Comment by p0we7** [comment]
发了

**Comment by laincat** [comment]
> 发了

期望更新 2.0

**Comment by sciooga** [comment]
> > 发了
> 
> 期望更新 2.0

Friefox 对 mv3 的支持有点问题，background 按 mv3 的标准是用 Service Work 来实现（Chrome、Edge 都是）但是目前 Firefox 还是以 background.js 的模式来执行，刚看更新计划有按标准来调整的规划了，但是得等等
