### ISSUE TITLE
请问现在Firefox应该怎么安装呢？

### ISSUE THREAD

**Issue by Mosney** [sciooga/v2ex-plus#161]
README里的链接提示已不存在

> 
> 哎呀！我们找不到那个页面
> 
> 如果您是点击其他网站上的链接而来，想寻找某个[扩展](https://addons.mozilla.org/zh-CN/firefox/extensions/)或[主题](https://addons.mozilla.org/zh-CN/firefox/themes/)，该项目却已不可用。这可能是因为：
> 
>     开发者主动下架。他们通常会因为不再支持该扩展或主题，或已推出替代版本而这么做。
>     Mozilla 已将其下架。这可能是因为在审核扩展或主题的过程中发现问题，或是该扩展或主题违反了 addons.mozilla.org 的使用条款和条件。开发者会有机会解决问题，并重新上架。
> 
> 请过段时间后再尝试访问该页面，因为主题或扩展可能会再次上架。另外，也许您可以在下列扩展或主题中找到要您要找的内容，或者到我们的[社区论坛](https://discourse.mozilla.org/c/add-ons)寻求帮助。

**Comment by wolnlow** [comment]
同问！

**Comment by p0we7** [comment]
因为新版重构用了新架构，而 firefox 不支持。
Firefox现在只能继续用旧版本。
