### ISSUE TITLE
回复中解析显示的图片太大

### ISSUE THREAD

**Issue by chenrylee** [sciooga/v2ex-plus#162]
如果回复中用了大图片，且被插件解析，则会显得图片非常夸张，比如[这个回复](https://www.v2ex.com/t/840777?p=1#r_11472064)。  

希望能在解析图片的时候，把图片限定在贴子的窗口本身大小，比如[这个回复](https://www.v2ex.com/t/840502?p=1#r_11467626)。  

比如取图片宽度为`min(img.width, 600)`。

**Comment by chenrylee** [comment]
我不会js，不过感觉这个应该是可以的：
```js
function get_img_width(url){
    var w;
    var img = new Image;
    img.src = url;
    img.onload = function() {
        w = this.width;
        if ( w > 600 ) {
            w = 600;
        }
    }
    return w;
}
```

然后把这个宽度放在`<img />`的标签里：
```js
let w = get_img_width(match);
<img src="${match}" width="${w}" /></a>;
```

**Comment by AcerFeng** [comment]
在这个问题还没修复前，可以用Stylish这个Chrome插件应急一下，新建一个自定义样式，加上下面的样式
```
a:not(a[onClick])>img:not(img[border]):not(img[id]) {
    max-width: 100%;
    height: auto;
}
```
应用对象记得只指定 v2ex.com 域名
