### ISSUE TITLE
chrome 安装过后几天内必失效，需要卸载重装

### ISSUE THREAD

**Issue by StillNotYet** [sciooga/v2ex-plus#164]
每天安装后几天内绝对失效，不知道是什么原因，卸载重装几天内又回这样。
windows 和 mac 都会

**Comment by chenrylee** [comment]
我也发现这个问题了，最开始还以为是Edge安装Chrome商店插件的原因，后来发现其它跨商店的都没问题，只有这个会失效。
不过如果用Chromium-based Edge + Edge商店版本就非常稳定。

**Comment by StillNotYet** [comment]
手动安装旧版本实测没问题

**Comment by Tomorrowxxy** [comment]
版本1.6.6 也遇到了

**Comment by eryajf** [comment]
+1

**Comment by eryajf** [comment]
> 手动安装旧版本实测没问题

手动安装之后，过两天又会自动更新到最新版，然后就又失效了，这个很烦

**Comment by StillNotYet** [comment]
> > 手动安装旧版本实测没问题
> 
> 手动安装之后，过两天又会自动更新到最新版，然后就又失效了，这个很烦

我的不会自动更新，你从仓库里下载安装 1.4.0 这个版本试试

**Comment by eryajf** [comment]
> 我的不会自动更新，你从仓库里下载安装 1.4.0 这个版本试试

我这边1.4.0版本貌似不行，用不了：

![image_20220726_102716](https://cdn.staticaly.com/gh/eryajf/tu/main/img/image_20220726_102716.png)

**Comment by StillNotYet** [comment]
> > 我的不会自动更新，你从仓库里下载安装 1.4.0 这个版本试试
> 
> 我这边1.4.0版本貌似不行，用不了：
> 
> ![image_20220726_102716](https://camo.githubusercontent.com/68a4fa6516085bb98c47f008c247ed012441e7e0bbfde27d31ba9064384f6463/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f657279616a662f74752f6d61696e2f696d672f696d6167655f32303232303732365f3130323731362e706e67)

我这边是可以的，你找下其他的方法试试
<img width="421" alt="image" src="https://user-images.githubusercontent.com/42577833/180909905-ee6dae4c-f81e-4387-94e7-c28226d8f5f8.png">

**Comment by chiperman** [comment]
v1.6.6 同样遇到了这个问题，卸载重装可以恢复正常，但是下午就失效了。自动签到功能是正常使用。
但是只看楼主、智能会话模式、悬浮头像显示信息、鼠标悬浮留言@用户显示此用户的发言等功能不可使用。

**Comment by P7XXTMX** [comment]
+1
