### ISSUE TITLE
The APPEND button is disabled a few seconds later after page load

### ISSUE THREAD

**Issue by volo1st** [sciooga/v2ex-plus#168]
Screen recording:
![output](https://user-images.githubusercontent.com/1330120/173283030-2914770a-b69d-4be2-a118-8830ad37eb70.gif)

- Extension version: 1.5.5 from Chrome store
- Chrome version: 102.0.5005.61 (Official Build) (64-bit)
- Distro Version: Ubuntu 20.04.4 LTS
- Kernel version: 5.13.0-44-generic

**Comment by p0we7** [comment]
version 2.0 is coming soon, please try again.
