### ISSUE TITLE
启用插件之后会有奇怪的footer高度

### ISSUE THREAD

**Issue by zzjin** [sciooga/v2ex-plus#17]
![image](https://cloud.githubusercontent.com/assets/679757/14280489/82492f4e-fb65-11e5-9271-f83039d9b72a.png)
![Uploading image.png…]()

 RT,装了插件之后每一个页面的footer下面有奇怪的间距
mac +chrome51

**Comment by sciooga** [comment]
感谢反馈，已经修复，等待更新吧。

**Comment by zzjin** [comment]
![image](https://cloud.githubusercontent.com/assets/679757/14310967/70e9a9b0-fc17-11e5-93ae-321ac1bc2adc.png)
还是没完全解决...
没有review吗...

**Comment by sciooga** [comment]
这个我还真忘了，太久以前写的代码了...现在也改好了，马上更新。
