### ISSUE TITLE
2.0版本部分功能失效了

### ISSUE THREAD

**Issue by solxnp** [sciooga/v2ex-plus#182]
如
回复楼层号（再回复时自动带上对方的楼层号）
快速查看相关用户（鼠标悬浮在 @用户 无任何反应）
楼主回复背景色

**Comment by chenrylee** [comment]
楼层号和OP背景色，我这边都是正常显示的。
目前发现的失效功能有：
1. 自动签到
2. 快速查看相关用户回复

**Comment by Jefffish09** [comment]
更新到2.0.0后发现“自动签到”失效了。

**Comment by sciooga** [comment]
以上问题已经修复，等待发布
20e1a21e9f7e050769ac5ededd5aaa8d2e0c6e13
