### ISSUE TITLE
“感谢爱心颜色”会影响到其它内容的颜色显示

### ISSUE THREAD

**Issue by chenrylee** [sciooga/v2ex-plus#183]
如图，设置的爱心颜色会影响到footer部分内容的颜色显示：  
<img width="582" alt="image" src="https://user-images.githubusercontent.com/10664121/221745616-964aa703-bd1d-4f20-8e01-c68ed6ba54cc.png">

**Comment by sciooga** [comment]
2.0.4 已修复
