### ISSUE TITLE
无法正常加载扩展

### ISSUE THREAD

**Issue by PPP1G** [sciooga/v2ex-plus#185]
![CleanShot 2023-03-02 at 11 23 35@2x](https://user-images.githubusercontent.com/56902719/222323034-39e0a0ed-40ca-49a5-97c0-e5681236b452.png)
所有功能都无法使用

**Comment by sciooga** [comment]
你好，重新安装也是这样吗？

**Comment by PPP1G** [comment]
以下方式均尝试过，都不起作用（早上刚打开电脑的时候有用了几分钟）
* 卸载后手动安装 1.6.5
* 卸载后手动安装 1.6.0
* 卸载后重新安装 2.0

**Comment by sciooga** [comment]
是官网的 Chrome 浏览器吗

**Comment by p0we7** [comment]
先关闭了，有问题再 comment。
