### ISSUE TITLE
更新2.0版本后自动签到失效

### ISSUE THREAD

**Issue by lppsuixn** [sciooga/v2ex-plus#186]
浏览器 edge
版本：chrome商店最新版本

前几天更新以后，这几天自动签到一直没工作过

**Comment by Panway** [comment]
Chrome110.0.5481.177 也没法自动签到

**Comment by Panway** [comment]
我平常访问的是https://v2ex.com ，刚打开调试控制台发现插件内部的接口url 写死成`https://www.v2ex.com`导致全部功能失效，重新打开 https://www.v2ex.com 发现楼主高亮等功能都能用

**Comment by zhuguanan** [comment]
升级2.0.1，还是不能自动签到，删除后重新安装，也不行

**Comment by Jefffish09** [comment]
升级2.0.1，还是不能自动签到 +1
Chrome 111.0.5563.65

**Comment by Panway** [comment]
@Jefffish09 你访问的是 https://www.v2ex.com 还是 https://v2ex.com ？

**Comment by Jefffish09** [comment]
> @Jefffish09 你访问的是 https://www.v2ex.com 还是 https://v2ex.com ？

@Panway 访问的是这个https://www.v2ex.com

**Comment by Panway** [comment]
我访问www开头的地址今天可以自动签到了，Chrome 110，我是卸载插件重新安装的

**Comment by zhuguanan** [comment]
我啥也没干，今天能自动签到了

**Comment by Jefffish09** [comment]
> 我访问www开头的地址今天可以自动签到了，Chrome 110，我是卸载插件重新安装的

@Panway 这两天发现，我啥都没做，它自己恢复正常了，能自动签到了。
