### ISSUE TITLE
‘最近查看过的主题’出现了我没有看过的帖子记录

### ISSUE THREAD

**Issue by shunia** [sciooga/v2ex-plus#192]
这是feature吗？请问如何关闭？我已经关闭了vDaily。

另外个人希望插件能尽量少的打扰到关键体验，对v2ex做增强是安装插件的目的，一些额外的feature建议做成完全可选的方式而非默认开启（比如vDaily），建议如果需要的话可以在第一次安装插件时默认打开选项页面并提示用户可选功能的opt in/out。

**Comment by p0we7** [comment]
第一次安装默认是打开选项页面的。

你用的是什么版本的扩展？

**Comment by shunia** [comment]
> 第一次安装默认是打开选项页面的。
> 
> 你用的是什么版本的扩展？

@p0we7 请问如何查看版本？我在Edge的管理页面和插件的选项页面都没看到，可能我看漏了。
我是在商店安装的，理论上是最新版本。

**Comment by p0we7** [comment]
Edge的管理页面认真看一下。

**Comment by shunia** [comment]
Version2.0.4
确实看漏了

**Comment by p0we7** [comment]
刷新一下页面，或者进入一下帖子应该会恢复。

**Comment by shunia** [comment]
> 刷新一下页面，或者进入一下帖子应该会恢复。

@p0we7 实测并不能哈，而且我已经试过清除缓存等简单的办法，基本都只能暂时的解决问题，然后不知道什么时候又会突然冒出一堆莫名其妙的`查看过的主题`。

所以我想先确认一下，这是功能还是BUG？

**Comment by p0we7** [comment]
有可能是 bug ，但是还不能确定问题在哪里。

**Comment by sciooga** [comment]
这个问题应该已经修复了，请确认
