### ISSUE TITLE
[需求]能不能给base64滑词解码后的结果右侧加一个复制的按钮？

### ISSUE THREAD

**Issue by hsingll** [sciooga/v2ex-plus#195]
现在滑词后解码会上浮一个弹窗，5s后去除，想要复制解码结果得手动选中再复制，遇上比较复杂的，5s过去了弹窗消失又复制不上。
能不能在弹窗中新增一个复制按钮，这样便于用户拿到解码结果。

谢谢！

**Comment by sciooga** [comment]
[#5380e86](https://github.com/sciooga/v2ex-plus/commit/5380e8632eb012d7530a76267ad17c4a4d53e3ed)
