### ISSUE TITLE
咨询下签到是什么逻辑

### ISSUE THREAD

**Issue by ansnail** [sciooga/v2ex-plus#196]
签到是不用打开v2，只要打开浏览器就行么，还是必须打开v2，两种情况我都试过，貌似都没有签到成功

**Comment by p0we7** [comment]
什么浏览器？

**Comment by sciooga** [comment]
打开功能，不打开 V 站时，每半小时判断一次当天是否有签到，签到过则不再尝试（如果切换过账号，第一个账号签到后，第二个账号登录了也不再尝试）

**Comment by sciooga** [comment]
之前一直不能复现，现在通过 edge 浏览器复现后已经修复了
https://github.com/sciooga/v2ex-plus/commit/ed4d07f9601f7fb5321bc974d13998c97325e983
