### ISSUE TITLE
点击会话详情的时候弹出的窗口中的对话能否定位到点击会话详情的楼层

### ISSUE THREAD

**Issue by addpd** [sciooga/v2ex-plus#197]
![image](https://user-images.githubusercontent.com/35485370/233533102-17082981-d143-463d-926d-2292d5da7ac9.png)
![image](https://user-images.githubusercontent.com/35485370/233533096-621b92a0-7d52-4b89-904f-32e636e8c560.png)
或者在弹出的窗口中添加一个定位到当前位置也行
看长会话看起来方便点

**Comment by sciooga** [comment]
现在新的楼中楼模式不知道是否能平替这个需求？

**Comment by Kirosca** [comment]
> 现在新的楼中楼模式不知道是否能平替这个需求？

可以👍👍👍
