### ISSUE TITLE
在edge上用chrome的版本，记不住开关

### ISSUE THREAD

**Issue by Mr54233** [sciooga/v2ex-plus#198]
rt，在edge dev上使用chrome商店的版本时，插件无法记住开关，换句话说就是开关失效，永远都是开启的状态无法关闭某些功能
换微软商店里的版本就可以开关，但是版本落后

**Comment by sciooga** [comment]
感谢反馈，2.0.7 版本的一个失误，已修复

https://github.com/sciooga/v2ex-plus/commit/f44e40904e01e0834956659e16c54a99c4ab5386
