### ISSUE TITLE
你火了啊https://v2ex.com/t/939486#reply107

### ISSUE THREAD

**Issue by bunnyblueair** [sciooga/v2ex-plus#199]
https://v2ex.com/t/939486#reply107

**Comment by p0we7** [comment]
你好，作者已经在原帖做了一个解释，可以查看下面的链接阅读。

https://v2ex.com/t/939486?p=2#r_13072133

**Comment by popokcn** [comment]
我感觉没啥问题，插件作者只是想做个排行榜，热帖的功能而言，然后在设置页也明显提示了。
反正我是无所谓，也就多几个请求而已，帮插件收集点数据而已

**Comment by zwb124** [comment]
啥时候把firefox的商店更新一下啊
