### ISSUE TITLE
鼠标移到头像上会使图片从48px 变到73px

### ISSUE THREAD

**Issue by hye** [sciooga/v2ex-plus#2]
鼠标移到头像上会使图片从48px 变到73px
原来的图片上没有大小约束，移上去那个加载的过程把它撑大了（ `loading.gif`:grey_question: 也是48px 啊 很奇怪 ）

**Comment by sciooga** [comment]
更新至 0.7.2 已解决这个问题，这个情况比较奇怪我还没弄清楚原因

**Comment by sciooga** [comment]
OK，解决了，如果你还是使用 0.7.1 版，只需在 v2ex 设置内打开高精度头像即可解决问题。
