### ISSUE TITLE
能否增加设置是否通知有人收藏帖子的开关？

### ISSUE THREAD

**Issue by zheeeng** [sciooga/v2ex-plus#20]
发一个帖子，一整天都在通知有人收藏了，可否增加一个开关不提示收藏？

**Comment by sciooga** [comment]
新消息提醒的实现方式可能和你想的不一样，是判断右侧栏 0 条未读提醒 是否存在而已。所以并不能具体的判断消息类型是收藏还是回复。
而且绝大部分的主题都是回复数大于收藏的，感觉这个需求不是特别必要。

**Comment by zheeeng** [comment]
@sciooga 现在V站小白用户增长快，还是有不少人只看和收藏不回帖的。如果直接 retrieve 一遍 https://www.v2ex.com/notifications，回复的条目有个 playload 类可以判断。不过作者觉得没有必要，那就尊重作者。我个人发现关闭消息通知才是清静之法。

**Comment by sciooga** [comment]
当初设计未读提醒时是考虑过 https://www.v2ex.com/notifications 这个页面，甚至底部的Atom Feed for Notifications，但是我个人在工作的地方都装了扩展，如果是靠这两个途径判断是否有未读消息那么只能判断最近一条消息的时间与保存的最近一次通知未读的时间是否相同，不同则提醒有新消息并记录该消息时间。

那么这样会有两个问题:
一个是办公室的电脑标记成未读了，但是回到家里的电脑还是会判断一次然后依旧会提醒然后保存最后一条消息的时间。
另一个是访问这个页面你将很难收到来自官方的未读提醒了，因为你访问过这个页面未读计数就会清零，如果你错过了扩展的提醒，那么这个未读消息很难及时的通知到用户。

由于上面两个原因我才采用判断右侧的未读提醒。当然会有更好的解决方法去把这个提醒做得更好，只不过时间有限，一直没能给出一个体验更好的方案。

PS: 我印象中如果有未读消息你不打开看的话，每5分钟还是会提醒你，所以遇到新消息方便的话还是打开看看好。
