### ISSUE TITLE
希望增加ipfs图片支持

### ISSUE THREAD

**Issue by chenjia404** [sciooga/v2ex-plus#200]
我做了一个ipfs的图床 https://cdn.ipfsscan.io/ ，在评论里面使用这个图床的时候，默认是不支持显示的，需要点开新窗口。
ipfs图床去中心化，免注册，还有部分浏览器原生支持，希望增加到支持的图床里面。

**Comment by p0we7** [comment]
不能显示是因为 v2 本身不支持，能显示是因为扩展另外做了修改。

这边建议直接提交 PR ，现在主要代码贡献者已经不打算继续投入开发了。
