### ISSUE TITLE
hover后自动展示查看对话体验很差

### ISSUE THREAD

**Issue by liaoliao666** [sciooga/v2ex-plus#201]
hover 上展示对话的功能很容易打乱后面贴子的位置，如果在看后面的帖子的时候，不小心展示对话，体验很糟糕。

**Comment by liaoliao666** [comment]
建议改成一个点击或hover按钮后触发

**Comment by p0we7** [comment]
这边建议直接提交 PR ，现在主要代码贡献者已经不打算继续投入开发了。

**Comment by zyronon** [comment]
@liaoliao666  可以试试这个脚本 https://greasyfork.org/zh-CN/scripts/458024-v2ex-next
