### ISSUE TITLE
是否支持标记, 屏蔽的人数据备份导出?

### ISSUE THREAD

**Issue by seth-shi** [sciooga/v2ex-plus#202]
貌似标记的人都只存在本地, 是否可以存储到云端(比如 V 站的某些字段中, 或者 webdav 或者部分开源服务: 做一个多存储驱动, 让用户选择)
也可以导出来再导入吧, 比如换个电脑就找不到其它服务了

**Comment by p0we7** [comment]
这边建议直接提交 PR ，现在主要代码贡献者已经不打算继续投入开发了。
