### ISSUE TITLE
跨页展开会话会不显示楼层本身

### ISSUE THREAD

**Issue by quericy** [sciooga/v2ex-plus#22]
![如图](http://i.imgur.com/OenPrVp.png)
https://v2ex.com/t/284211
109L展开后在会话中没有显示本身楼层.

**Comment by sciooga** [comment]
这个不是 bug 是 V 站的回复 API  并不是事实同步的（大概都有个几分钟的缓存），这会你再看看应该可以显示了。

**Comment by quericy** [comment]
原来如此~~
