### ISSUE TITLE
Firefox 48 强制扩展签名，扩展已经失效

### ISSUE THREAD

**Issue by liliang13** [sciooga/v2ex-plus#23]
修改 about:cofig 的一些方法也不可用。所以请问有没有提交签名的计划？或者能否发源码给我，我自己想办法。

谢谢

**Comment by sciooga** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/chrome-store-foxified/?src=cb-dl-updated

邮件沟通中在 Firefox 安装 Chrome 版成功
