### ISSUE TITLE
Firefox 安装 Chrome 版，如何更改默认选项

### ISSUE THREAD

**Issue by liulex** [sciooga/v2ex-plus#24]
找不到扩展的选项页面，请问应该如何更改选项设置？（主要是楼主回复背景色……

**Comment by sciooga** [comment]
你试试进入扩展的 /options.html

**Comment by liulex** [comment]
`进入扩展的 /options.html` 是指？
我能在 xpi 文件里看到有这个文件，但如果把 xpi 解包后改动然后打包回去，firefox 是不认的……

**Comment by sciooga** [comment]
抱歉，昨天比较忙，我一会试试

**Comment by sciooga** [comment]
这几天一直搞不定 Firefox 的翻墙(我两台 Mac 都不能用浏览器配置代理，linux 下又是正常的)...导致这么晚才能测试回复你，实在不好意思。

我测试了几个设置功能都是正常的，步骤如下。
1. 打开 V2EX 首页，右键预览按钮，选择查看元素。
![image](https://cloud.githubusercontent.com/assets/9958281/18030981/b4796190-6cfe-11e6-8a08-ff9cb4829de4.png)
1. 样式表内找到 v2ex_tab.css ，对其右键，复制位置
   ![image](https://cloud.githubusercontent.com/assets/9958281/18030988/e1071266-6cfe-11e6-844d-3cc1afe782b6.png)
2. 修改地址，并在新窗口打开。
   我这里复制得 moz-extension://3c340f2d-a810-1f4d-b83e-a3856cbf39ef/v2ex_tab.css
   将最后的 v2ex_tab.css 改成 options.html 即可，如：
   moz-extension://3c340f2d-a810-1f4d-b83e-a3856cbf39ef/options.html

**Comment by liulex** [comment]
帅气！非常感谢！:+1:
