### ISSUE TITLE
隐身模式下折叠主题无法显示展开按钮

### ISSUE THREAD

**Issue by quericy** [sciooga/v2ex-plus#25]
主题折叠时,在隐身窗口中无法显示展开按钮,也无法展开帖子内容

普通窗口浏览:

![如图所示](https://i.imgur.com/FR8PAQh.png)

隐身窗口中浏览:

![如图所示](https://i.imgur.com/3aTB327.png)

**Comment by sciooga** [comment]
确实是有这个问题，不过扩展主要是针对已登录状态下进行开发的，这个问题我记录了，争取下一版修复。
