### ISSUE TITLE
请问是否考虑增加 https 图床功能？

### ISSUE THREAD

**Issue by LeoMarX** [sciooga/v2ex-plus#28]
现在 V 站强制 https 了， chrome 对加载普通 http 图片链接会显示不安全。是否考虑增加 https 图床功能？

相关讨论：[/t/332167]( https://www.v2ex.com/t/332167 )

**Comment by sciooga** [comment]
会在近期将 新浪图床 和 imgur 新上传的图片地址改为 https。
