### ISSUE TITLE
「Chrome 版」未登录时，无法预览？

### ISSUE THREAD

**Issue by xuchunyang** [sciooga/v2ex-plus#3]
只能出标题，没有内容。不清楚是 V2EX API 的限制，还是实现上有什么问题？

**Comment by sciooga** [comment]
是的，这个问题我有发现，但是我觉得这是过于小众的需求所以没有适配，简单说就是你登陆后主题结尾会有“感谢”“收藏”这些按钮，预览功能是依靠正则截取主题内容的并以这几个按钮结束，而未登录是没有这些按钮所以导致只能截取到标题。
另外，如果未登录的话一些 CSS 样式可能会不够理想。

**Comment by xuchunyang** [comment]
好的。
