### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by realpg** [sciooga/v2ex-plus#30]
在复杂的讨论中，一个帖子可能会有同一个人的多次回复
后进入主题的人可能看到某人第一个回复就进行了针对性回答
可否在点击回复时候 不只是生成 at 某人 同时添加一个标记这是回复某人在某层楼的帖子
比如在@realpg 后面 自动添加一个#17 表示这是回复17楼的
同时快速review该人发言找如果有这个标记就显示这个楼层 而不是显示最后一个回复内容

**Comment by sciooga** [comment]
OK，是个好提议，争取下一个版本加上。
