### ISSUE TITLE
使用新浪图床，一直提示受到限制

### ISSUE THREAD

**Issue by hronro** [sciooga/v2ex-plus#31]
<img width="800" alt="截图" src="https://cloud.githubusercontent.com/assets/15059605/23194809/458a70a2-f8eb-11e6-911f-6993cfedc7f7.png">

### 提示如图，已经登录过网页版的微博了

**Comment by sciooga** [comment]
新浪微博网页版现在不能长时间保持登录状态了，请确认打开微博是否仍然是登录的？

**Comment by hronro** [comment]
@sciooga 
打开微博的时候，是已经登录了的

**Comment by sciooga** [comment]
提供一下你所使用的扩展版本号？我这里测试是正常的，或者看看扩展选项中图床的选择是否是微博？
