### ISSUE TITLE
提个建议，预览框悬浮于右侧

### ISSUE THREAD

**Issue by micln** [sciooga/v2ex-plus#4]
鼠标点击之后，像tooltips那样显示在右侧，这样加载过程中也不会感染继续往下读

不会描述，就像这个http://v3.bootcss.com/javascript/#-7

**Comment by sciooga** [comment]
如果宽度不等于 680px 那么排版就会被打乱，不是所有人的屏幕都那么宽的呀。
倒是可以考虑修改成悬浮框之类的，等我更新完0.8版会考虑下这个问题的。
谢谢~
