### ISSUE TITLE
今天连续出现签到错误

### ISSUE THREAD

**Issue by cikichen** [sciooga/v2ex-plus#42]
每隔一段时间就出现一次
![image](https://cloud.githubusercontent.com/assets/1478821/24089572/07fe926c-0d73-11e7-94a4-e3ba68ff7397.png)

**Comment by p0we7** [comment]
我今天签到正常 ， 可以选择关闭自动签到功能

**Comment by cikichen** [comment]
今天继续出错

**Comment by sciooga** [comment]
签到这个部分的代码已经重构，过段时间测试完成这个问题应该能得到解决
