### ISSUE TITLE
楼主回复背景的透明度无法调节

### ISSUE THREAD

**Issue by quericy** [sciooga/v2ex-plus#45]
如题，调节后无效果，重进设置页面发现被重置为0.4

**Comment by xspoco** [comment]
更新后好像不能设置选项了。。

**Comment by p0we7** [comment]
请问是最新版吗？麻烦提供扩展版本号与Chrome版本号

**Comment by quericy** [comment]
@xspoco 确实是部分选项失效了，目前发现：
+ 透明度不能保存
+ 感谢爱心颜色能保存但无效

@p0we7 扩展版本：`1.2.1` ，Chrome版本：`57.0.2987.98 (64-bit)`

**Comment by xspoco** [comment]
我的扩展也是最新的版本：`1.2.1`，360极速浏览器版本：`8.7.0.306`
现象是选项一个都点不了。
![image](https://cloud.githubusercontent.com/assets/19290455/24212966/ee18bf8a-0f6b-11e7-8099-c196b368fe96.png)

然后我试了Chrome 版本：`57.0.2987.110`，和 @quericy 说的现象一样。

**Comment by cratexnet** [comment]
同 Chrome 版本 `57.0.2987.110`
```
1、背景色透明度无法更改
2、感谢爱心颜色设置了但是无效
```

**Comment by p0we7** [comment]
最新版已经发布并可以安装 , 如果Chrome不自动更新可以删除后重新安装.

**Comment by xspoco** [comment]
360极速是被放弃了吗。。删除了重装依然不起作用。。。

@p0we7

**Comment by xspoco** [comment]
360极速的选项设置是打开一个新标签页，而不是和chrome一样弹出页设置的，是否和这个有关。

**Comment by sciooga** [comment]
@quericy #53 这里 @XY-e 提供了一个 360 兼容的版本
