### ISSUE TITLE
感谢❤的颜色无法更改，楼主回复的透明度无法修改，重置为0.4.

### ISSUE THREAD

**Issue by weigaow** [sciooga/v2ex-plus#46]
v2ex plus version 1.1.4
Chromium version 56.0.2924.87

**Comment by p0we7** [comment]
请尝试更新为最新版本

**Comment by weigaow** [comment]
目前可以看到的最新版就是1.1.2，sorry上面的信息有错误，我看到更新日志到了1.1.4，以为是最新版。
但是目前无法更新到最新版。
![snipaste20170323_002139](https://cloud.githubusercontent.com/assets/15966723/24208616/f6fcc02c-0f5e-11e7-8632-43610f64cf4b.png)

**Comment by p0we7** [comment]
最新版已经发布并可以安装 , 如果Chrome不自动更新可以删除后重新安装.
