### ISSUE TITLE
360极速浏览器用不了。

### ISSUE THREAD

**Issue by xspoco** [sciooga/v2ex-plus#53]
![image](https://cloud.githubusercontent.com/assets/19290455/24341088/c7ae60b2-12e9-11e7-822c-968b9c8a222b.png)
![image](https://cloud.githubusercontent.com/assets/19290455/24341110/f19af3fe-12e9-11e7-9f89-34ae40225fc7.png)

360极速浏览器 `8.7.0.306` 内核`50.0.2661.102`
v2ex plus `1.2.2`
Windows7 64bit

![image](https://cloud.githubusercontent.com/assets/19290455/24341891/a5837e54-12ef-11e7-93dc-a80647bd9f2b.png)

表现为选项都是灰色的，不能设置。不起作用。只有一个消息提醒是可以的。
新开了一个虚拟机，全新安装的win7，全新安装的360极速浏览器，只装v2ex plus一个插件。也是同样的情况。

然后我测试了下我机子上装的Chrome 版本 `50.0.2661.102 m`
也是同样的情况。

接着我更新了下Chrome最新版 `57.0.2987.110` 就没有这个问题了。
所以是Chrome内核的问题。。。？

**Comment by sciooga** [comment]
一些 API 有调整，我们正在做兼容

**Comment by gloomy-ghost** [comment]
激活 chrome://flags/#enable-javascript-harmony 试试？

**Comment by xspoco** [comment]
反馈下问题，感谢回复。
@sciooga 
那就等更新了。

@gloomy-ghost 
![image](https://cloud.githubusercontent.com/assets/19290455/24351437/374928ca-1318-11e7-9660-a52eaaddd711.png)
这个开启了，浏览器也重启了。 一样不起作用哦。

**Comment by gloomy-ghost** [comment]
在配置页按 F12 把 console 打开，看一下有什么报错之类的

**Comment by xspoco** [comment]
@gloomy-ghost 

![image](https://cloud.githubusercontent.com/assets/19290455/24355998/c4339ed4-132a-11e7-8ae3-31037b59ca93.png)

![image](https://cloud.githubusercontent.com/assets/19290455/24356010/d17695b0-132a-11e7-81f5-3540d189884f.png)

**Comment by gloomy-ghost** [comment]
看了下 MDN 的文档，对象的迭代从 Chrome 51 才有。推荐直接用最新版的 Chrome/Firefox，或者可以自己用 babel 转成兼容老式浏览器的代码之后再打包……

**Comment by xspoco** [comment]
感谢，自己搞的话没有这个技术。。
不用chrome是因为360极速是以前世界之窗极速一直用下来用的最顺手的chrome壳的浏览器。暂时没有找到一样顺手的chrome壳浏览器。。
看来只能等360极速更新了。

**Comment by gao03** [comment]
@xspoco  我修改成360极速可以用的了：
[v2ex-plus.zip](https://github.com/sciooga/v2ex-plus/files/884374/v2ex-plus.zip)

**Comment by xspoco** [comment]
@XY-e 已安装，可用。非常感谢！
