### ISSUE TITLE
多页时，查看回复的评论会卡死

### ISSUE THREAD

**Issue by lilydjwg** [sciooga/v2ex-plus#54]
扩展版本 0.6.9，火狐版本 52.0.1。

鼠标一移过去就会卡住，直接火狐提示脚本没有响应。只有一页时正常。

**Comment by gloomy-ghost** [comment]
这边没法重现，可以更新到[最新版](https://github.com/sciooga/v2ex-plus/releases/)再试试吗？ 
如果还是有问题的话请提供一个可以重现的链接

**Comment by lilydjwg** [comment]
用新版就好了。原来一直有新版，可是检查更新里没有啊……
