### ISSUE TITLE
选项错误换行

### ISSUE THREAD

**Issue by ivysrono** [sciooga/v2ex-plus#56]
![default](https://cloud.githubusercontent.com/assets/2649544/26527313/c99d29c0-43c3-11e7-8363-5e972e8f1654.png)

**Comment by xhhjin** [comment]
测试 Firefox 版发现这个问题，Chrome 没发现，下个版本修复。

**Comment by sciooga** [comment]
估计是当时太嚣张的用了 &nbsp 来排版导致的，我们会尽快处理的
