### ISSUE TITLE
Feature Request: Support Auto-blocking of Users Without Avatar

### ISSUE THREAD

**Issue by xfoxfu** [sciooga/v2ex-plus#59]

**Comment by sciooga** [comment]
抱歉一直没看到这个 issue
之前有人提过自动屏蔽默认头像，但是无法通过头像地址判断是否为默认头像，你有什么新的发现吗？

**Comment by xfoxfu** [comment]
我发现默认头像地址似乎和普通用户不同：

默认头像（Gravatar 生成）用户：<https://v2ex.assets.uxengine.net/gravatar/e100f0a15225b4ca06bba3dcf2b7b356?s=73&d=retro>

有 v2ex 头像用户：<https://v2ex.assets.uxengine.net/avatar/b758/6696/138436_large.png?m=1442316154>

有 Gravater 用户：<https://v2ex.assets.uxengine.net/gravatar/dee759256f7e18a6ad71aba938898dad?s=73&d=retro>

但如果把 Gravater 的 retro 参数设置为 404 的话，默认头像用户的图片就会返回 404 了。

例如：<https://v2ex.assets.uxengine.net/gravatar/e100f0a15225b4ca06bba3dcf2b7b356?s=73&d=404> 会返回 404.

<https://v2ex.assets.uxengine.net/gravatar/dee759256f7e18a6ad71aba938898dad?s=73&d=404> 会返回正常图片。

see: <https://stackoverflow.com/questions/32494796/determine-if-gravatar-return-default-image-using-javascript>

**Comment by sciooga** [comment]
真是思路新奇的判断方法，我们尝试下

**Comment by sciooga** [comment]
如果单纯在前端实现这个功能的话，效率不够高，即使缓存结果意义也不大（主题列表有 30+, 主题回复有 100），正在寻找新的方案，或者是引入后端进行批量查询及缓存。

**Comment by xfoxfu** [comment]
我觉得可以把开启了这个功能的用户的页面上的头像链接替换成 404，而不是单独做查询。这样返回 404 无头像对这些用户也没有影响，因为他们本来就看不到无头像的。

**Comment by sciooga** [comment]
现在的问题是，判断一个用户是否是默认头像需要一个发出请求（get参数为 d=404）然后通过响应来判断是否为 gravatar 头像，每个用户都需要发出一次请求才能知道是否为默认头像

**Comment by xfoxfu** [comment]
你可以用 Service Worker 拦截所有的发出请求，然后改为 404，并识别不存在的头像&屏蔽相关用户。

**Comment by sciooga** [comment]
根据目前的情况，估计只有我们开发个后端提供接口才能获得比较好的体验了，否则现有的方式体验效果都不是特别好。
