### ISSUE TITLE
连续两天出现"罕见错误"

### ISSUE THREAD

**Issue by quericy** [sciooga/v2ex-plus#6]
控制台页面报错信息:
![如图](http://i.imgur.com/3Jtknyc.png)

**Comment by sciooga** [comment]
谢谢反馈，这个问题我跟踪了很久，如果频繁出现的提示已经影响了您的使用可以暂时关掉自动签到。

目前主要怀疑是由于网络不稳定造成的，看你的出错记录可能是碰巧您这边尝试自动签到时遇到了 V 站的服务器错误。

**Comment by quericy** [comment]
看了下你的代码,感觉确实应该是网络原因,其实这种情况不alert也可以的,反正一小时后也会进行重试.

**Comment by quericy** [comment]
顺带,窗口非最大化时扩展设置页面左侧浮动div挡住右边的选项名称了 = =

**Comment by sciooga** [comment]
这个扩展还是写得比较乱的... 是之前自己用着觉得不错改了改发布，很多细节都不怎么样，代码风格也比较随意，那个设置页面得空就改一下。

如果不 alert 可能会漏签，一小时后也不一定成功的。
