### ISSUE TITLE
是否能增加回复楼层的开关

### ISSUE THREAD

**Issue by luboq** [sciooga/v2ex-plus#60]
同时在用v2ex-plus 和 V2EXcellent.js脚本，楼层序号会重复，且两个都不能关闭：
![](http://onuia4d7l.bkt.clouddn.com/2017_07_09_20170709172455.png)

**Comment by sciooga** [comment]
这倒不是什么难事，不过我更好奇 v2ex-plus 这有没有什么可以借鉴 V2EXcellent 这的功能？

**Comment by luboq** [comment]
@sciooga  其它倒可有可无，我只看重 V2EXcellent 的一个功能：评论堆叠

类似Reddit和HN。虽然v站回复不是一对一，难免不完美，但有总比没有强，对读帖很有帮助：
![](http://onuia4d7l.bkt.clouddn.com/2017_07_11_20170711201218.png)
![](http://onuia4d7l.bkt.clouddn.com/2017_07_11_20170711201616.png)
![](http://onuia4d7l.bkt.clouddn.com/2017_07_11_20170711201445.png)

**Comment by p0we7** [comment]
![](https://raw.githubusercontent.com/VitoVan/v2excellent.js/master/screenshots/gift-clickonce.png)

这个功能也不错 .

**Comment by sciooga** [comment]
v2ex plus 有一个类似的回话详情的功能

**Comment by p0we7** [comment]
Chrome Store 已更新,请等待扩展自动更新.(或者手动重新安装)
