### ISSUE TITLE
能否增加一个按键翻页功能。

### ISSUE THREAD

**Issue by xspoco** [sciooga/v2ex-plus#65]
不知道能否实现，
像discuz那样，帖子页，列表页，可以用键盘左右方向键翻页。。

**Comment by sciooga** [comment]
已完成，等待更新

**Comment by SilentDepth** [comment]
这个功能好像 overkill 了，在文本框里按左右也会触发，导致没法好好写回复了

**Comment by sciooga** [comment]
这两天忙了些，刚刚修复了，等待更新。

**Comment by p0we7** [comment]
@SilentDepth 新版已发布, 如果不能自动更新可以启用开发模式,手机更新.
