### ISSUE TITLE
“登陆”应改为“登录”才对，每次登录v2ex的时候都感觉怪怪的。

### ISSUE THREAD

**Issue by phpdever** [sciooga/v2ex-plus#69]
https://github.com/sciooga/v2ex-plus/blob/6edbe7d7aebc9a3bae77688c000f0539ddc7a80d/background.js#L225

**Comment by sciooga** [comment]
感谢提醒，已经改正

**Comment by p0we7** [comment]
最新版已发布在Chrome Store。
