### ISSUE TITLE
无法从Mozilla附加组件中心找到Firefox版插件

### ISSUE THREAD

**Issue by iF2007** [sciooga/v2ex-plus#7]
https://addons.mozilla.org/zh-CN/firefox/addon/v2ex-plus/
![fireshot screen capture 002 - - addons_mozilla_org_zh-cn_firefox_addon_v2ex-plus](https://cloud.githubusercontent.com/assets/4461848/10557494/c9dfe664-74e1-11e5-8016-42df2958be87.png)

**Comment by sciooga** [comment]
这两天更新后原链接就可用了。

**Comment by iF2007** [comment]
Thanks. This is a very useful addon. Cheers!

**Comment by sciooga** [comment]
Cheers! : )
