### ISSUE TITLE
Bug for searching replay.

### ISSUE THREAD

**Issue by lxzxl** [sciooga/v2ex-plus#70]
When a comment mentioned a user self, it failed to find the correct reply.

![v2ex-plux-bug](https://user-images.githubusercontent.com/2275002/30769645-30ca6f30-9fd2-11e7-9724-c3827fcf42ca.jpg)

**Comment by sciooga** [comment]
感谢 pr，这几天比较忙但是也让 @p0we7 测试了一下，不明白这个问题是否有修复，我简单看了下，这样处理不会影响到其他原来正常的情况吗？

**Comment by p0we7** [comment]
我也比较忙 , 这个星期都没怎么看v2

**Comment by gloomy-ghost** [comment]
verified as fixed
