### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ladit** [sciooga/v2ex-plus#72]
前几天想自己造轮子，发现这个拓展很好用就来提 issue 了，一下是一些建议：

1. 期待油猴脚本版，这样可以少装一个扩展，油猴脚本也可以设置自动和 Github 同步；
2. 个人认为 在 ID 后标记楼主（例如这个[脚本](https://greasyfork.org/zh-CN/scripts/3452)），加心改变底色 相比 楼主层改变底色，加心文字变色 是更好的展示方案，以下是我之前写的，可以根据加心数量调整 Alpha 值：

```
function highlightThankedReplies() {
  $("div.cell span.small.fade").each(function () {
    var rgba = "";
    var thankCount = Number($(this).text().slice(2));
    if (thankCount > 150) {
      rgba = "rgba(231, 116, 46, 1)";
    } else {
      rgba = "rgba(231, 116, 46, " + (0.005 * thankCount + 0.2) + ")";
    }
    $(this).parents("div.cell").css("background-color", rgba);
  });
}
```

![image](https://user-images.githubusercontent.com/16753453/31045238-bf5316e0-a611-11e7-8d90-3f3cc8c390ca.png)

3. 希望增加标题过滤功能，[参考](https://greasyfork.org/zh-CN/scripts/6231)。
我之前写的：

```
var toHideTitle = "招聘";
function titleFilter(toHideTitle) {
  toHideTitle = toHideTitle.toLocaleLowerCase();
  $('.cell.item').each(function () {
    if ($(this).find(".item_title").children().text().toLocaleLowerCase().search(toHideTitle) != -1) {
      $(this).remove();
    }
  });
}
```

4. 考虑适配 [f.v2ex](https://userstyles.org/styles/138175/f-v2ex) 这个主题，似乎在这个主题下预览帖子按钮换行了，而且需要双击，而且 mouseover 的下划线太长：
![image](https://user-images.githubusercontent.com/16753453/31045353-5bf965b0-a614-11e7-926f-b218fb9f66d5.png)

5. 不确定是否在 f.v2ex 主题下，双击返回顶部失效；

6. 似乎在 f.v2ex 主题下，回复框上方的插入图片、表情按钮丢失；

感谢！

**Comment by sciooga** [comment]
楼主底色是可以自定义的，感谢的星星也能自定义一个颜色，同样很突出，标题过滤的功能会考虑加上，适配主题相关的问题可能就忙不过来了（如果你有时间可以考虑处理一下）

**Comment by ladit** [comment]
我的意思是需要用底色突出的应该是被感谢的楼层，楼主反而没有那么必要用底色突出，在 ID 后标记这是楼主就可以了。
另外期待油猴脚本版，这样可以少装一个扩展，油猴脚本也可以设置自动和 Github 同步。

**Comment by p0we7** [comment]
ID后标记楼主这个功能本来是想集成进来的 , 但是我不好意思要求这么多就只集成了签到的代码.

**Comment by sciooga** [comment]
@p0we7 这个功能自己实现也是可以的啊
