### ISSUE TITLE
关注特定帖子

### ISSUE THREAD

**Issue by Sneezry** [sciooga/v2ex-plus#74]
好像没有关注特定帖子的功能，如果这个功能目前还没有开发计划我可以contribute

**Comment by p0we7** [comment]
非常欢迎

**Comment by sciooga** [comment]
虽然项目代码质量可能有些差，但是很高兴你能 contribute ，如果有需要进一步沟通可以联系我： sciooga@gmail.com

**Comment by Sneezry** [comment]
As the PR has been merged, this issue is closed.
