### ISSUE TITLE
imgur 会限制国内上传次数？

### ISSUE THREAD

**Issue by EchoChan314** [sciooga/v2ex-plus#78]
![snipaste20171128_153132.png](https://i.loli.net/2017/11/28/5a1d112b536d5.png)

我设置的图床是imgur 。不用微博，所以没选微博图床。

**Comment by sciooga** [comment]
因为 imgur 接口改动后，无法使用自己的 imgur 上传图片了，所以现在是大家公用一个匿名账号（这个匿名账号是由 imgur 接口提供的），每天确实是有上传限制

**Comment by EchoChan314** [comment]
@sciooga  所以目前除了注册个微博账号登陆来用微博图床这方法外还有解吗？

**Comment by sciooga** [comment]
暂时没办法了
