### ISSUE TITLE
支持imgchr可否？

### ISSUE THREAD

**Issue by EchoChan314** [sciooga/v2ex-plus#79]
https://imgchr.com/page/plugin

表示微博没账号，imgur被限制。

**Comment by xmcp** [comment]
V2EX支持其他图床吗？

**Comment by EchoChan314** [comment]
@xmcp 回复是只有 Default 语法，不支持 Markdown 的
https://www.v2ex.com/t/293527

看来没戏了

**Comment by sciooga** [comment]
V2EX 只支持三个图床，上面说的之外，还有一个官方自己的

**Comment by sciooga** [comment]
我们抽时间处理下 imgur 的问题，可能会是注册多一些账号随机抽取来上传，因为目前扩展的用户比以前多了挺多了

**Comment by sciooga** [comment]
新增了 5 个，共 6 个 imgur 的 key 请等待更新
