### ISSUE TITLE
Firefox v2ex plus link return not found

### ISSUE THREAD

**Issue by timwangdev** [sciooga/v2ex-plus#8]
> Firefox 版：v2ex plus

链接打开后火狐显示找不到页面
https://addons.mozilla.org/zh-CN/firefox/addon/v2ex-plus/

**Comment by sciooga** [comment]
不好意思，该扩展由于一些 DOM 操作不符合 Mozilla 的规范被下架了，由于时间原因我一时半会没法重写这部分代码，所以这个链接只有当我更新扩展的时候才能恢复正常。

更具体的原因： https://www.v2ex.com/t/210599?p=2#r_2659564 118楼

感谢你的反馈 : )
