### ISSUE TITLE
使用sov2ex替换默认搜索？

### ISSUE THREAD

**Issue by ryh** [sciooga/v2ex-plus#80]
https://www.sov2ex.com/
https://github.com/bynil/sov2ex/blob/master/API.md

**Comment by sciooga** [comment]
这个项目的作者我记得也给我提过，我当时在主题中答应有时间啊就处理，没想到一拖再拖到今天...
看来需要找一些时间更充裕的朋友加入到这个项目了

**Comment by wwjdoodlemail** [comment]
我做了一个 "使用sov2ex替换默认搜索", 可以加进来 吗？
Ubuntu 17.04 （64 位）
Chromium 62.0.3202.89 测试通过
![sov2ex](https://user-images.githubusercontent.com/716854/34426661-fcce11a2-ec73-11e7-94b3-7fc9860aedc5.png)

**Comment by ryh** [comment]
@wwjdoodlemail 我以为是那种类似algolia的instant search 呢 结果还是跳网页
看看这个
https://github.com/algolia/github-awesome-autocomplete/

**Comment by sciooga** [comment]
@wwjdoodlemail 可以提交 pr 我们合并一下

**Comment by sciooga** [comment]
我们已经加入，请等待更新
