### ISSUE TITLE
插件在新同步下，会默认启用双击返回顶部功能

### ISSUE THREAD

**Issue by kslr** [sciooga/v2ex-plus#85]
双击就会返回顶部，本来是复制。
然后检查了一下插件双击返回顶部功能没有打开，这边电脑插件都是新同步过来的， 从未设置过。
然后取消了插件，功能消失；重新开启插件后恢复正常，返回顶部没有工作。

**Comment by UnluckyNinja** [comment]
更新后可能读取旧设置出问题了，我一直没有开启过这个功能，最近突然就默认双击回顶部了。重置设置后正常了。BTW这个功能和划词翻译严重冲突……

**Comment by sciooga** [comment]
这个问题已经发现并且修复，今晚发布新版本，抱歉了...
