### ISSUE TITLE
Feature request: 希望能把自动签到的通知提醒关掉...

### ISSUE THREAD

**Issue by toinfty** [sciooga/v2ex-plus#87]
打开自动签到之后，每隔一段时间都有自动签到的提醒，希望能加一个选项把这个提醒关掉... 

谢谢！

**Comment by sciooga** [comment]
是弹出上面提醒？签到成功后当日就不会再次提醒了的

**Comment by toinfty** [comment]
多谢回复！签到成功后的确不会提醒了。

不过可以彻底（无论成功与否）关闭这个签到提醒么？

谢谢！

**Comment by sciooga** [comment]
可以是可以，但是担心的就是签到失败没提醒会导致断签，我们可以做一个默认打开的的开关

**Comment by sciooga** [comment]
开关已增加，下一版本发布后就有了
