### ISSUE TITLE
微博相册支持https了

### ISSUE THREAD

**Issue by ohyooo** [sciooga/v2ex-plus#89]
https://photo.weibo.com 可以正常访问了
要不要考虑修改一下插件里的协议 o(*^＠^*)o
我之前是开着 https everywhere 的，所以每次都得关掉才能上传（排除微博域名什么的，强迫症受不了啦 o(￣ヘ￣o＃)）

**Comment by sciooga** [comment]
明白啦，下一版本更新

**Comment by sciooga** [comment]
因为我们用的接口是 picupload.service.weibo.com 之前测试 https 是正常的，但是这两天又出问题了，可能还是得将微博上传图片接口换回 http
