### ISSUE TITLE
怎么在火狐 43+ 里使用呢？

### ISSUE THREAD

**Issue by lilydjwg** [sciooga/v2ex-plus#9]
火狐 43+ 要求所有扩展都签名……

**Comment by sciooga** [comment]
如果禁止从非官方市场安装扩展的话，可能一时半会也没有什么好的办法... 当某次我更新官方市场的版本号时我想办法通知你，你就可以从官方市场下载安装了。

或者你留下联系方式我把 Firefox 的源码发你，你自己找找办法？

**Comment by lilydjwg** [comment]
我找到绕过的方法了：设置 xpinstall.signatures.required;false。
