### ISSUE TITLE
非登录状态下无法展开过长的主题

### ISSUE THREAD

**Issue by trim21** [sciooga/v2ex-plus#90]
chrome版本 66.0.3359.139（正式版本） （64 位）

https://www.v2ex.com/t/452325

问题发生在这个帖子

![](https://ws1.sinaimg.cn/large/bd69bf14ly1fr136y549aj20sa0akab1.jpg)

console有一个报错
```
v2ex_reply.js:449 Uncaught TypeError: Cannot read property 'parentNode' of null
    at v2ex_reply.js:449
```

**Comment by sciooga** [comment]
你好，目前扩展在非登录状态下有不少 Bug，建议登录使用，未登录状态暂时没有更多的时间进行兼容，抱歉了。
