### ISSUE TITLE
新增的修改复制和粘贴内容的权限是用于什么功能呢？（2018.6.12）

### ISSUE THREAD

**Issue by Weilor** [sciooga/v2ex-plus#91]

**Comment by gloomy-ghost** [comment]
源码都在这了……
https://github.com/sciooga/v2ex-plus/commit/8a18d7185d56376e6a5fb88cb767c9f829893d1b

**Comment by sciooga** [comment]
你好，是为了实现 Decode base64 后，复制到剪切板:

https://github.com/sciooga/v2ex-plus/commit/8a18d7185d56376e6a5fb88cb767c9f829893d1b

剪切板目前所有操作都是写入，没有读取，源码就是 GitHub 这份，大家可以放心。

其实写入剪切板本身是不需要申请权限的[1]，这是新加入项目的小伙伴完成的功能，参考的是 Chrome Ext 的开发文档示例（里面展示的剪切板操作带有写入和读取，以及如何申请权限），下一版本会让他修改去掉这个权限，因为我们没有读取的需要，抱歉。

[1]. 之前不需权限即可写入剪切板:
https://github.com/sciooga/v2ex-plus/blob/master/v2ex_reply.js#L147

Duplicate of #92
