### ISSUE TITLE
更新后chrome提示需要新的授权：修改您复制和粘贴的数据，请问下这个是什么功能需要，之前好像没有这个

### ISSUE THREAD

**Issue by goodryb** [sciooga/v2ex-plus#92]
更新后chrome提示需要新的授权，请问下这个是什么功能需要，之前好像没有这个
![image](https://user-images.githubusercontent.com/3907975/41266056-df8901a2-6e27-11e8-84bf-af61373dafbc.png)

**Comment by sciooga** [comment]
你好，是为了实现 Decode base64 后，复制到剪切板:

https://github.com/sciooga/v2ex-plus/commit/8a18d7185d56376e6a5fb88cb767c9f829893d1b

剪切板目前所有操作都是写入，没有读取，源码就是 GitHub 这份，大家可以放心。

其实写入剪切板本身是不需要申请权限的[1]，这是新加入项目的小伙伴完成的功能，参考的是 Chrome Ext 的开发文档示例（里面展示的剪切板操作带有写入和读取，以及如何申请权限），下一版本会让他修改去掉这个权限，因为我们没有读取的需要，抱歉。

[1]. 之前不需权限即可写入剪切板:
https://github.com/sciooga/v2ex-plus/blob/master/v2ex_reply.js#L147

**Comment by paicha** [comment]
右键 decode base64 这个功能，太画蛇添足了。

**Comment by goodryb** [comment]
好的，多谢，前面close的issue没看到，提重复了。
