### ISSUE TITLE
通过 Chrome 通知会同时打开十几个提醒页

### ISSUE THREAD

**Issue by love4taylor** [sciooga/v2ex-plus#93]
通过图标打开则正常只有一个
![](https://wx4.sinaimg.cn/large/af997d39gy1fu19fmst7gj211y0lctet.jpg)

**Comment by sciooga** [comment]
请问您使用的浏览器是？版本号为？这个 Bug 不太应该会出现的。

**Comment by love4taylor** [comment]
@sciooga Chrome 70.0.3510.0 (Official Build) dev (64-bit), 不过也不是每次都是并且也不是每次都是十几个标签, 也会出现七八个的情况, 也有单一个的情况.

**Comment by sciooga** [comment]
你这边的系统是不是 linux ？我们测试了这么长一段时间没有遇到这样的情况，会不会是和系统平台有关？

**Comment by love4taylor** [comment]
@sciooga 恩, 可能确实和 Linux 有关, 我也没在其他平台试过.

**Comment by sciooga** [comment]
那我先关闭这个 issue 了，这个估计是和你系统的原生通知系统有些关系，暂时无能为力...
