### ISSUE TITLE
Windows native notifications support

### ISSUE THREAD

**Issue by zhoukuncheng** [sciooga/v2ex-plus#95]
Chrome 68现在支持Windows原生通知中心了，但是从v2ex+的通知，点击后不会跳转到相应的帖子，
YouTube之类网页的web notification没有问题

**Comment by sciooga** [comment]
能打开未读消息的网页吗?

**Comment by zhoukuncheng** [comment]
@sciooga 也打不开，点击后消息直接消失了

**Comment by sciooga** [comment]
我们这进行了测试，似乎是可以打开的，能否截图下弹出的通知？我很久没有 windows 了，不太懂现在弹出的是原生通知中心的还是 Chrome 自己弹出的

**Comment by zhoukuncheng** [comment]
![image](https://user-images.githubusercontent.com/5327960/44627459-06743100-a961-11e8-8484-897a1d9ba231.png)

就是这样的通知，是Windows通知中心里的，
之前走Chrome自己的通知，确实没问题

**Comment by sciooga** [comment]
系统版本号和浏览器版本号是？

**Comment by zhoukuncheng** [comment]
Windows 10 1803

**Comment by sciooga** [comment]
这个 bug 应该是 chrome 还未兼容好新系统导致的，我们也没办法进行处理

**Comment by ghost** [comment]
现在已经可以正常打开了
