### ISSUE TITLE
开启扩展后，回复不显示换行

### ISSUE THREAD

**Issue by iDvel** [sciooga/v2ex-plus#96]
一个多行的回复，会被自动折叠到同一行。

我是 macOS 10.14，Firefox 61.0.2。
试了下 Chrome 的没问题。

例子：
![](https://i.imgur.com/O2JYH3d.png)

**Comment by sciooga** [comment]
V2EX 之前没对换行和多个空格处理，导致换行和多个空格都是显示为一个空格，所以扩展是将其还原了原来的排版

Firefox 版可能是这部分的还原功能有些异常，没能还原，你先试试关掉扩展这个回复是不是和开启扩展是一样的排版，是的话应该就是 Firefox 版有些异常了。

如果是 Firefox 版不正常可以尝试直接在 Firefox 内安装 Chrome 版（具体见网上很多教程），相比于 Firefox 版也多了很多功能

**Comment by iDvel** [comment]
@sciooga 刚知道还有这种操作，已经在 Firefox 上安装了 Chrome 版的插件，谢谢。

**Comment by xhhjin** [comment]
@iDvel Firefox 扩展这两天已经更新了，问题已修复。
