### ISSUE TITLE
很久没收到新消息提醒了

### ISSUE THREAD

**Issue by lilydjwg** [sciooga/v2ex-plus#97]
最近好几次发现 v2ex 有新未读消息，但是我没有收到提醒。难道是每一次提醒出现的时候我都正好不在电脑前么……

火狐 nightly，扩展是 amo 上的最新版。

PS: 我把图标从界面上删掉了。这个应该没有影响吧……

**Comment by sciooga** [comment]
火狐版仍然在更新但是速度会慢一些 @xhhjin ，着急的话可以试试在 Firefox 安装 Chrome 商店的版本（具体操作请搜索教程）

**Comment by lilydjwg** [comment]
不着急，就是来问问。

**Comment by xhhjin** [comment]
确实有问题，有消息时图标会变化但无提醒。原因： Firefox 的 notification 不支持 buttons，导致出错了，https://github.com/mdn/webextensions-examples/issues/340 ，后面改下。

**Comment by xhhjin** [comment]
@lilydjwg 新版本已修复此问题，请更新 AMO 上的最新版本。
