### ISSUE TITLE
[enhancement] Use sm.ms instead of weibo&imgur

### ISSUE THREAD

**Issue by kmahyyg** [sciooga/v2ex-plus#98]
Because of the reason we all know,

- The weibo image storage may leak your username.
- The imgur may not be accessible in most of China mainland.

So, Why not try SM.MS?

API Here: https://sm.ms/doc/
TOS Here: https://sm.ms/about/

**Comment by sciooga** [comment]
https://www.v2ex.com/faq

V2EX 支持三个图床，微博、imgur、v2ex
