### ISSUE TITLE
能否在主题列表添加 achieve 按钮? 等同于 收藏 + 忽略

### ISSUE THREAD

**Issue by xiao-po** [sciooga/v2ex-plus#99]
如果可以的话加这个简便的功能，我感觉现在对于一部分的人来说挺需要这种功能。

**Comment by sciooga** [comment]
你好，是收藏并忽略的意思吗？

发自我的 iPhone

**Comment by xiao-po** [comment]
是的

> 你好，是收藏并忽略的意思吗？ 发自我的 iPhone
> […](#)
> 在 2018年12月26日，下午4:50，x_po ***@***.***> 写道： 如果可以的话加这个简便的功能，我感觉现在对于一部分的人来说挺需要这种功能。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sciooga** [comment]
你好，调研了下，似乎呼声不算大，可能得麻烦你多点几下鼠标了，或者觉得实在有必要的话，你可以完成这个功能（需要能通过设置进行配置，默认关闭）然后提交 pr，谢谢
